[package]
name = "ethers-abi-enc"
version = "0.1.0"
edition = "2021"
description = "Ethereum ABI encoding and decoding"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/ethers-rs/core"
readme = "README.md"
keywords = ["ethereum", "abi", "encoding", "EVM", "solidity"]
categories = ["encoding", "serialization", "cryptocurrency", "ethereum"]
authors = []

[dependencies]
ethers-primitives = { version = "0.1.0", path = "../primitives" }
hex = "0.4.3"

sol-type-parser = { version = "0.1.0", path = "sol-type-parser", optional = true }
thiserror = { version = "1.0.39", optional = true }
serde = { version = "1.0.159", optional = true }
tiny-keccak = { version = "2.0.2", optional = true, features = ["keccak"] }

[dev-dependencies]
hex-literal = "0.3.4"

[features]
default = ["std", "dynamic", "eip712"]
std = ["hex/std", "thiserror"]
dynamic = ["std"]
eip712 = ["dep:tiny-keccak", "dep:sol-type-parser"]
eip712-serde = ["dep:serde", "eip712"]
